package tests:component@0.1.0;

world test {
    use types.{entity};

    include type-tests;

    export register-entity: func(e: entity);
    export register-entities: func(e: list<entity>);
    export get-entity: func(id: s32) -> entity;
    export get-entities: func() -> list<entity>;

    export set-flag: func(flag: bool);
    export get-flag: func() -> bool;
    export get-host-entity-description: func() -> string;

    export sum-nested-list: func(nested: list<list<u32>>) -> u32;

    export host-callback: func();
    export host-combine-string: func(s1: string, s2: string) -> string;

    import callback: func();
    import callback-combine-string: func(s1: string, s2: string) -> string;
    import get-host-entity: func() -> entity;
}
