package tests:test@0.1.0;

world test {
    export add-u8: func(x: u8, y: u8) -> u8;
    export add-s8: func(x: s8, y: s8) -> s8;
    export add-u16: func(x: u16, y: u16) -> u16;
    export add-s16: func(x: s16, y: s16) -> s16;
    export add-u32: func(x: u32, y: u32) -> u32;
    export add-s32: func(x: s32, y: s32) -> s32;
    export add-u64: func(x: u64, y: u64) -> u64;
    export add-s64: func(x: s64, y: s64) -> s64;
    export add-f32: func(x: f32, y: f32) -> f32;
    export add-f64: func(x: f64, y: f64) -> f64;

    export uppercase: func(s: string) -> string;

    export set-flag: func(flag: bool);
    export get-flag: func() -> bool;
}
